#!/bin/bash
# sorry I stuck some bash into my ruby...lol

if { cd ~/ 2> /dev/null; pwd; }
then
    echo it worked
else
    echo cd failed
    exit 1
fi

echo "let's continue"


for ((i=1; i<=5; i++))
do
    if [ $i -gt 2 ] && [ $i -ne 3 ]; then
        echo $i;
    elif [ $i -eq 3 ]; then
        echo $i is finally greater than two;
    else
        echo Not greater than 2 yet...
    fi
done

for name in Harry Mike Charles Tom
do
    echo $name
done

for word in This is a long sentence that I just made up
do
    echo $word
done
