puts "
START
# A METHOD THAT TAKES A INTEGER ARRAY RETURNING EVERY OTHER ELEMENT

DEFINE METHOD NAME AND PASS INTEGER_ARRAY
FIND LENGTH INDEXES
FIND INDEX OF FIRST ELEMENT OF INTEGER_ARRAY
SET VALUE OF FIRST ELEMENT OF INTEGER_ARRAY TO A NEW ARRAY
SET ITERATOR TO 2
FOR LENGTH OF INDEXES, APPEND INDEX VALUE OF EACH INTERATION TO NEW ARRAY
PRINT NEW ARRAY
END METHOD DEFINITION

END
\n"

