puts "
START
# A METHOD THAT RETURNS THE SUM OF TWO INTEGERS

DEFINE METHOD NAME AND PASS TWO ARGUMENTS
SET NUMBER_SUM = FIRST_ARGUMENT + SECOND ARGUMENT
PRINT NUMBER_SUM
END METHOD DEFINITION

END
\n"

