puts "
START
# A METHOD THAT TAKES A STRING ARRAY AND RETURNS ONE CONCATENATED STRING

DEFINE METHOD NAME AND PASS STRING_ARRAY
# IF JOIN METHOD AVAILABLE
SET JOINED_STRING = STRING_ARRAY #USE JOIN METHOD
#ELSE 
ITERATE STRING_ARRAY AND APPEND EACH STRING TO JOINED_STRING VARIABLE
#END STRATEGY
PRINT JOINED_STRING
END METHOD DEFINITION

END
\n"

